#ifndef CORAL_CONCURRENCY_IMPL
#define CORAL_CONCURRENCY_IMPL

/*! \file */

#include "common/targets.h"



// CONCURRENCY

//- IMPLEMENTATION RESOLUTION

#if CORAL_IS_TARGET(CORAL_TARGET_WIN32)
#   define CORAL_CONCURRENCY_IMPL_WIN32
#elif CORAL_IS_TARGET(CORAL_TARGET_LINUX)
#   define CORAL_CONCURRENCY_IMPL_LINUX
#endif

#endif
