#ifndef CORAL_GRAPHICS_INPUT
#define CORAL_GRAPHICS_INPUT

/*! \file */



// USER INPUT

/*! \defgroup CORAL_GRAPHICS_INPUT Input
 *  \ingroup CORAL_GRAPHICS
 *  \brief Definitions of input buttons and keys.
 *  \see \p Window_MouseInputCallbackFunc_t and \p Window_KeyboardInputCallbackFunc_t to actually receive input.
 *  \see \p Window_MouseMoveCallbackFunc_t to receive mouse movement input.
 *  \addtogroup CORAL_GRAPHICS_INPUT
 *  @{
 */



//- DEFINITIONS

//- - INPUT MODIFIERS

/*! \defgroup CORAL_GRAPHICS_INPUT_MODIFIERS Input modifiers
 *  \brief Special buttons that may change the meaning of received input.
 *  \addtogroup CORAL_GRAPHICS_INPUT_MODIFIERS
 *  @{
 */

#define CORAL_GRAPHICS_INPUT_MODIFIER_CTRL              (0x0001U)
#define CORAL_GRAPHICS_INPUT_MODIFIER_ALT               (0x0002U)
#define CORAL_GRAPHICS_INPUT_MODIFIER_SHIFT             (0x0004U)
#define CORAL_GRAPHICS_INPUT_MODIFIER_MOUSE_PRIMARY     (0x0100U)
#define CORAL_GRAPHICS_INPUT_MODIFIER_MOUSE_SECONDARY   (0x0200U)
#define CORAL_GRAPHICS_INPUT_MODIFIER_MOUSE_MIDDLE      (0x0400U)
#define CORAL_GRAPHICS_INPUT_MODIFIER_MOUSE_EXTRA1      (0x0800U)
#define CORAL_GRAPHICS_INPUT_MODIFIER_MOUSE_EXTRA2      (0x1000U)

/*! @} */



//- - MOUSE BUTTONS

/*! \defgroup CORAL_GRAPHICS_INPUT_MOUSE Mouse input
 *  \brief Input received from the mouse.
 *  \addtogroup CORAL_GRAPHICS_INPUT_MOUSE
 *  @{
 */

typedef enum {
    CORAL_GRAPHICS_INPUT_MOUSE_PRIMARY = 1,
    CORAL_GRAPHICS_INPUT_MOUSE_SECONDARY,
    CORAL_GRAPHICS_INPUT_MOUSE_MIDDLE,
    CORAL_GRAPHICS_INPUT_MOUSE_EXTRA1,
    CORAL_GRAPHICS_INPUT_MOUSE_EXTRA2
} MouseInput_e;

/*! @} */



//- - KEYBOARD BUTTONS

/*! \defgroup CORAL_GRAPHICS_INPUT_KEYBOARD Keyboard input
 *  \brief Input received from the mouse.
 *  \addtogroup CORAL_GRAPHICS_INPUT_KEYBOARD
 *  @{
 */

typedef enum {
    CORAL_GRAPHICS_INPUT_KEYBOARD_ESCAPE = 1,
    CORAL_GRAPHICS_INPUT_KEYBOARD_ENTER,
    CORAL_GRAPHICS_INPUT_KEYBOARD_TAB,
    CORAL_GRAPHICS_INPUT_KEYBOARD_SPACE,
    CORAL_GRAPHICS_INPUT_KEYBOARD_BACKSPACE,
    CORAL_GRAPHICS_INPUT_KEYBOARD_A,
    CORAL_GRAPHICS_INPUT_KEYBOARD_B,
    CORAL_GRAPHICS_INPUT_KEYBOARD_C,
    CORAL_GRAPHICS_INPUT_KEYBOARD_D,
    CORAL_GRAPHICS_INPUT_KEYBOARD_E,
    CORAL_GRAPHICS_INPUT_KEYBOARD_F,
    CORAL_GRAPHICS_INPUT_KEYBOARD_G,
    CORAL_GRAPHICS_INPUT_KEYBOARD_H,
    CORAL_GRAPHICS_INPUT_KEYBOARD_I,
    CORAL_GRAPHICS_INPUT_KEYBOARD_J,
    CORAL_GRAPHICS_INPUT_KEYBOARD_K,
    CORAL_GRAPHICS_INPUT_KEYBOARD_L,
    CORAL_GRAPHICS_INPUT_KEYBOARD_M,
    CORAL_GRAPHICS_INPUT_KEYBOARD_N,
    CORAL_GRAPHICS_INPUT_KEYBOARD_O,
    CORAL_GRAPHICS_INPUT_KEYBOARD_P,
    CORAL_GRAPHICS_INPUT_KEYBOARD_Q,
    CORAL_GRAPHICS_INPUT_KEYBOARD_R,
    CORAL_GRAPHICS_INPUT_KEYBOARD_S,
    CORAL_GRAPHICS_INPUT_KEYBOARD_T,
    CORAL_GRAPHICS_INPUT_KEYBOARD_U,
    CORAL_GRAPHICS_INPUT_KEYBOARD_V,
    CORAL_GRAPHICS_INPUT_KEYBOARD_W,
    CORAL_GRAPHICS_INPUT_KEYBOARD_X,
    CORAL_GRAPHICS_INPUT_KEYBOARD_Y,
    CORAL_GRAPHICS_INPUT_KEYBOARD_Z,
    CORAL_GRAPHICS_INPUT_KEYBOARD_0,
    CORAL_GRAPHICS_INPUT_KEYBOARD_1,
    CORAL_GRAPHICS_INPUT_KEYBOARD_2,
    CORAL_GRAPHICS_INPUT_KEYBOARD_3,
    CORAL_GRAPHICS_INPUT_KEYBOARD_4,
    CORAL_GRAPHICS_INPUT_KEYBOARD_5,
    CORAL_GRAPHICS_INPUT_KEYBOARD_6,
    CORAL_GRAPHICS_INPUT_KEYBOARD_7,
    CORAL_GRAPHICS_INPUT_KEYBOARD_8,
    CORAL_GRAPHICS_INPUT_KEYBOARD_9
} KeyboardInput_e;

/*! @} */

/*! @} */

#endif
