#ifndef CORAL_GRAPHICS_WINDOWING_IMPL
#define CORAL_GRAPHICS_WINDOWING_IMPL

/*! \file */

#include "common/targets.h"



// WINDOWING

//- IMPLEMENTATION RESOLUTION

#if CORAL_IS_TARGET(CORAL_TARGET_WIN32)
#   define CORAL_GRAPHICS_WINDOWING_IMPL_WIN32
#else
#   define CORAL_GRAPHICS_WINDOWING_IMPL_NULL
#endif

#endif
